### ISSUE TITLE
Player crashes when trying to load a playlist that contains a video that has been deleted/unlisted

### ISSUE THREAD

**Issue by DMNz3** [GreatArcStudios/Equator#3]
Not that much of a big issue, but I keep big playlists and sometimes certain songs get taken down and whenever I try opening one without checking whether or not all videos are available the player crashes.
Other than that perfect 5/7.

**Comment by GreatArcStudios** [comment]
Fixed in latest release.

**Comment by DMNz3** [comment]
You sir, are amazing! Kudos~
